version: '2'

services:
  alertmanager:
    image: bitnami/alertmanager:latest
    volumes:
      - ./alertmanager/slackalert.yml:/opt/bitnami/alertmanager/conf/config.yml
    ports:
      - 9093:9093
    environment:
      - SLACK_API_CREDENTIALS_URL

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/config:/etc/prometheus/
    ports:
      - 9090:9090
    environment:
      - BEARER_TOKEN

  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    depends_on:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USERNAME}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}